[formatting]
align_entries         = true
column_width          = 100
compact_arrays        = false
reorder_inline_tables = true
reorder_keys          = true

[[rule]]
include = [ "**/Cargo.toml" ]
keys    = [ "package" ]

[rule.formatting]
reorder_keys = false

[[rule]]
include = [ "**/Cargo.toml" ]
keys    = [ "profile" ]

[rule.formatting]
reorder_keys = false
