[package]
name = "tree-sitter"
description = "Rust bindings to the Tree-sitter parsing library"
version = "0.3.3"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
build = "build.rs"
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing"]
categories = ["api-bindings", "parsing", "text-editors"]

include = [
  "/build.rs",
  "/Cargo.toml",
  "/LICENSE",
  "/README.md",
  "/src/*",
  "/vendor/tree-sitter/externals/utf8proc/utf8proc*",
  "/vendor/tree-sitter/include/*",
  "/vendor/tree-sitter/src/runtime/*",
]

[dependencies]
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[build-dependencies]
cc = "1.0"
