[workspace]
default-members = ["cli"]
members = ["cli", "cli/config", "cli/loader", "lib", "tags", "highlight"]
resolver = "2"

[workspace.package]
rust-version = "1.70"

[profile.optimize]
inherits = "release"
strip = true         # Automatically strip symbols from the binary.
lto = true           # Link-time optimization.
opt-level = 3        # Optimization level 3.
codegen-units = 1    # Maximum size reduction optimizations.

[profile.size]
inherits = "optimize"
opt-level = "s"       # Optimize for size.

[profile.profile]
inherits = "optimize"
strip = false

[workspace.dependencies]
ansi_term = "0.12.1"
anstyle = "1.0.6"
anyhow = "1.0.79"
cc = "1.0.83"
clap = { version = "4.5.0", features = [
  "cargo",
  "derive",
  "env",
  "help",
  "unstable-styles",
] }
ctor = "0.2.6"
ctrlc = { version = "3.4.2", features = ["termination"] }
difference = "2.0.0"
dirs = "5.0.1"
fs4 = "0.7.0"
glob = "0.3.1"
html-escape = "0.2.13"
indexmap = "2.2.2"
indoc = "2.0.4"
lazy_static = "1.4.0"
libloading = "0.8.1"
log = { version = "0.4.20", features = ["std"] }
memchr = "2.7.1"
once_cell = "1.19.0"
path-slash = "0.2.1"
pretty_assertions = "1.4.0"
rand = "0.8.5"
regex = "1.10.3"
regex-syntax = "0.8.2"
rustc-hash = "1.1.0"
semver = "1.0.21"
serde = { version = "1.0.196", features = ["derive"] }
serde_derive = "1.0.196"
serde_json = { version = "1.0.113", features = ["preserve_order"] }
smallbitvec = "2.5.1"
tempfile = "3.10.0"
thiserror = "1.0.56"
tiny_http = "0.12.0"
toml = "0.8.10"
unindent = "0.2.3"
walkdir = "2.4.0"
wasmparser = "0.121.0"
webbrowser = "0.8.12"
which = "6.0.0"
