[workspace]
default-members = ["cli"]
members = [
  "cli",
  "cli/config",
  "cli/loader",
  "lib",
  "lib/language",
  "tags",
  "highlight",
  "xtask",
]
resolver = "2"

[workspace.package]
version = "0.24.4"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
edition = "2021"
rust-version = "1.74.1"
homepage = "https://tree-sitter.github.io/tree-sitter"
repository = "https://github.com/tree-sitter/tree-sitter"
license = "MIT"
keywords = ["incremental", "parsing"]
categories = ["command-line-utilities", "parsing"]

[profile.optimize]
inherits = "release"
strip = true         # Automatically strip symbols from the binary.
lto = true           # Link-time optimization.
opt-level = 3        # Optimization level 3.
codegen-units = 1    # Maximum size reduction optimizations.

[profile.size]
inherits = "optimize"
opt-level = "s"       # Optimize for size.

[profile.release-dev]
inherits = "release"
lto = false
debug = true
debug-assertions = true
overflow-checks = true
incremental = true
codegen-units = 256

[workspace.dependencies]
anstyle = "1.0.8"
anyhow = "1.0.89"
bstr = "1.10.0"
cc = "1.1.22"
clap = { version = "4.5.18", features = [
  "cargo",
  "derive",
  "env",
  "help",
  "unstable-styles",
] }
clap_complete = "4.5.29"
ctor = "0.2.8"
ctrlc = { version = "3.4.5", features = ["termination"] }
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
dirs = "5.0.1"
filetime = "0.2.25"
fs4 = "0.9.1"
git2 = "0.19.0"
glob = "0.3.1"
heck = "0.5.0"
html-escape = "0.2.13"
indexmap = "2.5.0"
indoc = "2.0.5"
lazy_static = "1.5.0"
libloading = "0.8.5"
log = { version = "0.4.22", features = ["std"] }
memchr = "2.7.4"
once_cell = "1.19.0"
path-slash = "0.2.1"
pretty_assertions = "1.4.1"
rand = "0.8.5"
regex = "1.10.6"
regex-syntax = "0.8.4"
rustc-hash = "2.0.0"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = { version = "1.0.128", features = ["preserve_order"] }
similar = "2.6.0"
smallbitvec = "2.5.3"
streaming-iterator = "0.1.9"
tempfile = "3.12.0"
thiserror = "1.0.64"
tiny_http = "0.12.0"
toml = "0.8.19"
unindent = "0.2.3"
url = { version = "2.5.2", features = ["serde"] }
walkdir = "2.5.0"
wasmparser = "0.217.0"
webbrowser = "1.0.2"

tree-sitter = { version = "0.24.4", path = "./lib" }
tree-sitter-generate = { version = "0.24.4", path = "./cli/generate" }
tree-sitter-loader = { version = "0.24.4", path = "./cli/loader" }
tree-sitter-config = { version = "0.24.4", path = "./cli/config" }
tree-sitter-highlight = { version = "0.24.4", path = "./highlight" }
tree-sitter-tags = { version = "0.24.4", path = "./tags" }
