[package]
name = "tree-sitter-cli"
description = "CLI tool for developing, testing, and using Tree-sitter parsers"
version = "0.21.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "tree-sitter"
path = "src/main.rs"
doc = false

[[bench]]
name = "benchmark"
harness = false

[features]
wasm = ["tree-sitter/wasm", "tree-sitter-loader/wasm"]

[dependencies]
ansi_term.workspace = true
anstyle.workspace = true
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
difference.workspace = true
dirs.workspace = true
glob.workspace = true
html-escape.workspace = true
indexmap.workspace = true
indoc.workspace = true
lazy_static.workspace = true
log.workspace = true
memchr.workspace = true
path-slash.workspace = true
regex.workspace = true
regex-syntax.workspace = true
rustc-hash.workspace = true
semver.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
smallbitvec.workspace = true
tiny_http.workspace = true
walkdir.workspace = true
wasmparser.workspace = true
webbrowser.workspace = true
which.workspace = true

[dependencies.tree-sitter]
version = "0.21.0"
path = "../lib"

[dependencies.tree-sitter-config]
version = "0.21.0"
path = "config"

[dependencies.tree-sitter-highlight]
version = "0.21.0"
path = "../highlight"

[dependencies.tree-sitter-loader]
version = "0.21.0"
path = "loader"

[dependencies.tree-sitter-tags]
version = "0.21.0"
path = "../tags"

[dev-dependencies]
tree_sitter_proc_macro = { path = "src/tests/proc_macro", package = "tree-sitter-tests-proc-macro" }

rand.workspace = true
tempfile.workspace = true
pretty_assertions.workspace = true
ctor.workspace = true
unindent.workspace = true

[build-dependencies]
toml.workspace = true
