[book]
authors = [
  "Max Brunsfeld <maxbrunsfeld@gmail.com>",
  "Amaan Qureshi <amaanq12@gmail.com>",
]
language = "en"
multilingual = false
src = "src"
title = "Tree-sitter"

[output.html]
additional-css = ["src/assets/css/playground.css"]
additional-js = ["src/assets/js/playground.js"]
git-repository-url = "https://github.com/tree-sitter/tree-sitter"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/tree-sitter/tree-sitter/edit/master/docs/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true

[output.html.redirect]
"/syntax-highlighting.html" = "/3-syntax-highlighting.html"
"/code-navigation-systems" = "/4-code-navigation.html"
"/implementation" = "/5-implementation.html"
"/contributing" = "/6-contributing.html"
"/playground" = "/7-playground.html"
