[package]
name = "tree-sitter-config"
description = "User configuration of tree-sitter's command line programs"
version = "0.19.0"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing"]
categories = ["command-line-utilities", "parsing"]
repository = "https://github.com/tree-sitter/tree-sitter"
rust-version.workspace = true

[dependencies]
anyhow = "1.0"
dirs = "3.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]
